version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_merch
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: merch-shop  # Название базы данных
      POSTGRES_USER: admin  # Имя пользователя
      POSTGRES_PASSWORD: admin  # Пароль
    volumes:
      - db_data_merch:/var/lib/postgresql/data  # Хранение данных
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Скопировать init.sql в контейнер

  app:
    image: openjdk:17-jdk-alpine  # Используем образ с JDK 17
    container_name: merch_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Проброс порта
    depends_on:
      - db  # Приложение зависит от базы данных
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/merch-shop  # URL подключения к базе данных
      SPRING_DATASOURCE_USERNAME: admin  # Имя пользователя
      SPRING_DATASOURCE_PASSWORD: admin  # Пароль базы данных
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Автоматическое создание схемы

volumes:
  db_data_merch:
